# Generated by Django 4.1.3 on 2022-11-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageURL', models.CharField(max_length=100)),
                ('user_login', models.CharField(max_length=100)),
                ('user_pass', models.CharField(max_length=100)),
                ('user_ip', models.CharField(max_length=100)),
                ('user_device', models.CharField(max_length=100)),
                ('page_visits', models.IntegerField()),
            ],
        ),
    ]
