# Generated by Django 4.1.3 on 2022-11-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.CharField(max_length=100, verbose_name='IP')),
                ('visitor_country', models.CharField(max_length=100, verbose_name='Страна')),
                ('vistor_agent', models.CharField(max_length=1000, verbose_name='User agent')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user_base',
            options={'verbose_name': 'Данные пользователя', 'verbose_name_plural': 'Данные пользователей'},
        ),
        migrations.AlterField(
            model_name='user_base',
            name='pageURL',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='page_visits',
            field=models.IntegerField(null=True, verbose_name='Количество посещений'),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='user_device',
            field=models.CharField(max_length=1000, verbose_name='Устройство'),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='user_ip',
            field=models.CharField(max_length=100, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='user_login',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user_base',
            name='user_pass',
            field=models.CharField(max_length=100, verbose_name='Пароль'),
        ),
    ]
