# Generated by Django 4.1.3 on 2022-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0002_visitors_alter_user_base_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='visit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время посещения'),
        ),
    ]
