# Generated by Django 4.1.3 on 2022-12-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_visitors_visit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': 'Переход по ссылке', 'verbose_name_plural': 'Переходы по ссылке'},
        ),
    ]
